import type { SeedData } from './types';

export const seedData: SeedData = {
  users: [
    { userId: 'u1', name: 'Jay Martinez', role: 'Admin', operator: 'Permian Energy Corp' },
    { userId: 'u2', name: 'Sarah Chen', role: 'OperatorUser', operator: 'Permian Energy Corp', county: 'Reeves' },
    { userId: 'u3', name: 'Mike Torres', role: 'Analyst', operator: 'Permian Energy Corp' },
    { userId: 'u4', name: 'Diana Reeves', role: 'Auditor' },
    { userId: 'u5', name: 'Tom Baker', role: 'ReadOnly' },
  ],
  accessPolicy: {
    policyId: 'pol-001',
    rolePolicies: [
      { role: 'Admin', canCreate: true, canSubmit: true, canApprove: true, canView: true, canExport: true, canAdmin: true },
      { role: 'OperatorUser', canCreate: true, canSubmit: true, canApprove: false, canView: true, canExport: false, canAdmin: false },
      { role: 'Analyst', canCreate: false, canSubmit: false, canApprove: false, canView: true, canExport: true, canAdmin: false },
      { role: 'Auditor', canCreate: false, canSubmit: false, canApprove: true, canView: true, canExport: true, canAdmin: false },
      { role: 'ReadOnly', canCreate: false, canSubmit: false, canApprove: false, canView: true, canExport: false, canAdmin: false },
    ],
    sodRules: [
      { ruleId: 'sod-001', description: 'Submitter cannot approve own artifacts', constraint: 'submittedBy != approvedBy' },
      { ruleId: 'sod-002', description: 'Two distinct roles required for approval chain', constraint: 'roles.distinct >= 2' },
    ],
  },
  evidenceRequirements: [
    { requirementId: 'req-001', artifactType: 'Permit', requiredFor: ['COMPLIANCE_STATUS'], appliesToAssetTypes: ['LEASE','WELL'], mandatory: true, description: 'Drilling permit from RRC', rules: 'Valid permit required before spud' },
    { requirementId: 'req-002', artifactType: 'OperatorIdentityProof', requiredFor: ['COMPLIANCE_STATUS'], appliesToAssetTypes: ['LEASE'], mandatory: true, description: 'P-5 Organization Report', rules: 'Operator identity must be verified' },
    { requirementId: 'req-003', artifactType: 'W-1', requiredFor: ['COMPLIANCE_STATUS','SUBMODEL_APPROVAL'], appliesToAssetTypes: ['WELL'], mandatory: true, description: 'RRC W-1 Drilling Permit Application', rules: 'W-1 must be filed before spud date' },
    { requirementId: 'req-004', artifactType: 'W-2', requiredFor: ['COMPLIANCE_STATUS'], appliesToAssetTypes: ['WELL'], mandatory: true, description: 'RRC W-2 Oil Well Potential Test', rules: 'W-2 required after completion' },
    { requirementId: 'req-005', artifactType: 'G-1', requiredFor: ['COMPLIANCE_STATUS'], appliesToAssetTypes: ['WELL'], mandatory: false, description: 'RRC G-1 Gas Well Status Report', rules: 'G-1 for gas wells only' },
    { requirementId: 'req-006', artifactType: 'H-10', requiredFor: ['COMPLIANCE_STATUS'], appliesToAssetTypes: ['WELL'], mandatory: false, description: 'RRC H-10 Disposal Permit', rules: 'H-10 for disposal/injection wells' },
    { requirementId: 'req-007', artifactType: 'Completion', requiredFor: ['SUBMODEL_APPROVAL'], appliesToAssetTypes: ['WELL'], mandatory: true, description: 'Well Completion Report', rules: 'Required after well completion' },
    { requirementId: 'req-008', artifactType: 'ProductionReport', requiredFor: ['SUBMODEL_APPROVAL'], appliesToAssetTypes: ['WELL'], mandatory: true, description: 'Monthly Production Volumes', rules: 'Monthly production filing' },
    { requirementId: 'req-009', artifactType: 'SharedEquipmentDoc', requiredFor: ['COMPLIANCE_STATUS'], appliesToAssetTypes: ['PAD'], mandatory: true, description: 'Pad-level Shared Equipment Doc', rules: 'Document shared separators/tanks' },
    { requirementId: 'req-010', artifactType: 'AllocationMethodology', requiredFor: ['SUBMODEL_APPROVAL'], appliesToAssetTypes: ['PAD'], mandatory: false, description: 'Allocation Methodology', rules: 'Required if emissions tracked at pad' },
    { requirementId: 'req-011', artifactType: 'IntegrityTest', requiredFor: ['COMPLIANCE_STATUS'], appliesToAssetTypes: ['WELL','EQUIPMENT'], mandatory: true, description: 'Mechanical Integrity Test', rules: 'Periodic MIT testing required' },
    { requirementId: 'req-012', artifactType: 'Calibration', requiredFor: ['SUBMODEL_APPROVAL'], appliesToAssetTypes: ['EQUIPMENT'], mandatory: true, description: 'Equipment Calibration Certs', rules: 'Annual calibration records' },
  ],
  envelopes: [
    {
      aasId: 'basin-001', assetType: 'BASIN', name: 'Permian Basin', operator: 'Multiple', county: 'Multiple',
      identifiers: { globalId: 'urn:aas:basin:permian', rrcId: 'PB-001', apiNumber: '' },
      relations: { parent: null, children: ['field-001'] },
      submodels: [
        { type: 'Reserves', version: 1, status: 'ACTIVE', met: 1, total: 1, missing: [] },
        { type: 'Regulatory', version: 1, status: 'ACTIVE', met: 1, total: 1, missing: [] },
      ],
      events: [], evidenceArtifacts: [], complianceStatus: 'COMPLIANT', compliancePct: 100,
    },
    {
      aasId: 'field-001', assetType: 'FIELD', name: 'Wolfcamp Field', operator: 'Permian Energy Corp', county: 'Reeves',
      identifiers: { globalId: 'urn:aas:field:wolfcamp', rrcId: 'WF-001', apiNumber: '' },
      relations: { parent: 'basin-001', children: ['lease-001'] },
      submodels: [
        { type: 'Production', version: 1, status: 'ACTIVE', met: 1, total: 1, missing: [] },
        { type: 'Reserves', version: 1, status: 'ACTIVE', met: 1, total: 1, missing: [] },
        { type: 'Regulatory', version: 1, status: 'ACTIVE', met: 2, total: 2, missing: [] },
      ],
      events: [], evidenceArtifacts: [], complianceStatus: 'COMPLIANT', compliancePct: 100,
    },
    {
      aasId: 'lease-001', assetType: 'LEASE', name: 'Wolfcamp Unit A', operator: 'Permian Energy Corp', county: 'Reeves',
      identifiers: { globalId: 'urn:aas:lease:wolfcamp-a', rrcId: 'LA-001', apiNumber: '' },
      relations: { parent: 'field-001', children: ['pad-001'] },
      submodels: [
        { type: 'Production', version: 2, status: 'ACTIVE', met: 2, total: 2, missing: [] },
        { type: 'Reserves', version: 1, status: 'ACTIVE', met: 1, total: 1, missing: [] },
        { type: 'Emissions', version: 1, status: 'DRAFT', met: 0, total: 1, missing: ['AllocationMethodology'] },
        { type: 'Regulatory', version: 1, status: 'ACTIVE', met: 2, total: 2, missing: [] },
        { type: 'Accounting', version: 1, status: 'ACTIVE', met: 1, total: 1, missing: [] },
        { type: 'Ownership_Contracts', version: 1, status: 'ACTIVE', met: 1, total: 1, missing: [] },
      ],
      events: [], evidenceArtifacts: ['art-008'], complianceStatus: 'COMPLIANT', compliancePct: 95,
    },
    {
      aasId: 'pad-001', assetType: 'PAD', name: 'Wolfcamp Pad A', operator: 'Permian Energy Corp', county: 'Reeves',
      identifiers: { globalId: 'urn:aas:pad:wolfcamp-a', rrcId: 'PA-001', apiNumber: '' },
      relations: { parent: 'lease-001', children: ['well-001','well-002'] },
      submodels: [
        { type: 'Production', version: 2, status: 'ACTIVE', met: 2, total: 2, missing: [] },
        { type: 'Emissions', version: 1, status: 'DRAFT', met: 1, total: 2, missing: ['AllocationMethodology'] },
        { type: 'Regulatory', version: 1, status: 'ACTIVE', met: 1, total: 1, missing: [] },
        { type: 'Operations_SCADA', version: 3, status: 'ACTIVE', met: 2, total: 2, missing: [] },
        { type: 'Risk_Controls', version: 1, status: 'ACTIVE', met: 2, total: 2, missing: [] },
      ],
      events: ['ev-007'], evidenceArtifacts: ['art-005'], complianceStatus: 'PARTIAL', compliancePct: 85,
    },
    {
      aasId: 'well-001', assetType: 'WELL', name: 'Wolfcamp A-1H', operator: 'Permian Energy Corp', county: 'Reeves',
      identifiers: { globalId: 'urn:aas:well:wolfcamp-a-1h', rrcId: 'WL-001', apiNumber: '42-389-12345' },
      relations: { parent: 'pad-001', children: ['equip-001'] },
      submodels: [
        { type: 'Production', version: 2, status: 'ACTIVE', met: 2, total: 2, missing: [] },
        { type: 'Reserves', version: 1, status: 'ACTIVE', met: 1, total: 1, missing: [] },
        { type: 'Emissions', version: 1, status: 'ACTIVE', met: 1, total: 1, missing: [] },
        { type: 'Regulatory', version: 2, status: 'ACTIVE', met: 5, total: 5, missing: [] },
        { type: 'Accounting', version: 1, status: 'ACTIVE', met: 1, total: 1, missing: [] },
        { type: 'Operations_SCADA', version: 3, status: 'ACTIVE', met: 2, total: 2, missing: [] },
        { type: 'Ownership_Contracts', version: 1, status: 'ACTIVE', met: 1, total: 1, missing: [] },
        { type: 'Risk_Controls', version: 1, status: 'ACTIVE', met: 2, total: 2, missing: [] },
        { type: 'Evidence_Provenance', version: 1, status: 'ACTIVE', met: 5, total: 5, missing: [] },
      ],
      events: ['ev-001','ev-002','ev-003','ev-004','ev-006'],
      evidenceArtifacts: ['art-001','art-002','art-003','art-006','art-007','art-008'],
      complianceStatus: 'COMPLIANT', compliancePct: 100,
    },
    {
      aasId: 'well-002', assetType: 'WELL', name: 'Wolfcamp A-2H', operator: 'Permian Energy Corp', county: 'Reeves',
      identifiers: { globalId: 'urn:aas:well:wolfcamp-a-2h', rrcId: 'WL-002', apiNumber: '42-389-12346' },
      relations: { parent: 'pad-001', children: [] },
      submodels: [
        { type: 'Production', version: 1, status: 'DRAFT', met: 0, total: 2, missing: ['ProductionReport','Completion'] },
        { type: 'Regulatory', version: 1, status: 'DRAFT', met: 0, total: 4, missing: ['W-1','W-2','Permit','IntegrityTest'] },
        { type: 'Operations_SCADA', version: 1, status: 'DRAFT', met: 0, total: 1, missing: ['SCADA Config'] },
        { type: 'Risk_Controls', version: 1, status: 'DRAFT', met: 0, total: 2, missing: ['IntegrityTest','SoD Review'] },
      ],
      events: ['ev-005'],
      evidenceArtifacts: ['art-004'],
      complianceStatus: 'NON_COMPLIANT', compliancePct: 15,
    },
    {
      aasId: 'equip-001', assetType: 'EQUIPMENT', name: 'Separator S-101', operator: 'Permian Energy Corp', county: 'Reeves',
      identifiers: { globalId: 'urn:aas:equip:sep-s101', rrcId: 'EQ-001', apiNumber: '' },
      relations: { parent: 'well-001', children: [] },
      submodels: [
        { type: 'Operations_SCADA', version: 2, status: 'ACTIVE', met: 1, total: 1, missing: [] },
        { type: 'Risk_Controls', version: 1, status: 'ACTIVE', met: 1, total: 1, missing: [] },
      ],
      events: [], evidenceArtifacts: [], complianceStatus: 'COMPLIANT', compliancePct: 100,
    },
  ],
  artifacts: [
    { artifactId: 'art-001', aasId: 'well-001', artifactType: 'W-1', title: 'W-1 Drilling Permit - Wolfcamp A-1H', fileHash: 'sha256:ff01aa23', fileName: 'W1_A1H.pdf', status: 'APPROVED', submittedBy: 'Sarah Chen', submittedAt: '2026-01-15', approvedBy: 'Diana Reeves', approvedAt: '2026-01-16', version: 1 },
    { artifactId: 'art-002', aasId: 'well-001', artifactType: 'W-2', title: 'W-2 Potential Test - Wolfcamp A-1H', fileHash: 'sha256:ff02bb34', fileName: 'W2_A1H.pdf', status: 'PENDING', submittedBy: 'Sarah Chen', submittedAt: '2026-02-01', version: 1 },
    { artifactId: 'art-003', aasId: 'well-001', artifactType: 'Completion', title: 'Completion Report - A-1H', fileHash: 'sha256:ff03cc45', fileName: 'Comp_A1H.pdf', status: 'APPROVED', submittedBy: 'Sarah Chen', submittedAt: '2026-01-20', approvedBy: 'Jay Martinez', approvedAt: '2026-01-21', version: 1 },
    { artifactId: 'art-004', aasId: 'well-002', artifactType: 'W-1', title: 'W-1 Drilling Permit - Wolfcamp A-2H', fileHash: 'sha256:ff04dd56', fileName: 'W1_A2H.pdf', status: 'REJECTED', submittedBy: 'Mike Torres', submittedAt: '2026-02-08', rejectedBy: 'Diana Reeves', rejectedAt: '2026-02-10', rejectionNote: 'Missing formation interval data in Section 4. Resubmit with geological survey.', version: 1 },
    { artifactId: 'art-005', aasId: 'pad-001', artifactType: 'SharedEquipmentDoc', title: 'Shared Separator Doc - Pad A', fileHash: 'sha256:ff05ee67', fileName: 'Equip_PadA.pdf', status: 'APPROVED', submittedBy: 'Sarah Chen', submittedAt: '2026-01-10', approvedBy: 'Jay Martinez', approvedAt: '2026-01-11', version: 1 },
    { artifactId: 'art-006', aasId: 'well-001', artifactType: 'IntegrityTest', title: 'MIT Results - A-1H', fileHash: 'sha256:ff06ff78', fileName: 'MIT_A1H.pdf', status: 'APPROVED', submittedBy: 'Sarah Chen', submittedAt: '2026-02-15', approvedBy: 'Diana Reeves', approvedAt: '2026-02-16', version: 1 },
    { artifactId: 'art-007', aasId: 'well-001', artifactType: 'ProductionReport', title: 'Production Jan 2026 - A-1H', fileHash: 'sha256:ff07aa89', fileName: 'Prod_Jan_A1H.pdf', status: 'APPROVED', submittedBy: 'Sarah Chen', submittedAt: '2026-02-05', approvedBy: 'Diana Reeves', approvedAt: '2026-02-06', version: 1 },
    { artifactId: 'art-008', aasId: 'well-001', artifactType: 'Permit', title: 'Drilling Permit - A-1H', fileHash: 'sha256:ff08bb90', fileName: 'Permit_A1H.pdf', status: 'APPROVED', submittedBy: 'Sarah Chen', submittedAt: '2026-01-05', approvedBy: 'Jay Martinez', approvedAt: '2026-01-06', version: 1 },
  ],
  approvals: [
    { approvalId: 'apr-001', artifactId: 'art-001', submittedBy: 'Sarah Chen', approvedBy: 'Diana Reeves', decision: 'APPROVED', timestamp: '2026-01-16T14:00:00Z', notes: 'All sections verified against geological survey.' },
    { approvalId: 'apr-002', artifactId: 'art-003', submittedBy: 'Sarah Chen', approvedBy: 'Jay Martinez', decision: 'APPROVED', timestamp: '2026-01-21T10:00:00Z', notes: 'Completion data matches drilling report.' },
    { approvalId: 'apr-003', artifactId: 'art-004', submittedBy: 'Mike Torres', approvedBy: 'Diana Reeves', decision: 'REJECTED', timestamp: '2026-02-10T11:00:00Z', notes: 'Missing formation interval data in Section 4.' },
    { approvalId: 'apr-004', artifactId: 'art-005', submittedBy: 'Sarah Chen', approvedBy: 'Jay Martinez', decision: 'APPROVED', timestamp: '2026-01-11T09:00:00Z', notes: 'Equipment inventory verified on-site.' },
  ],
  events: [
    { eventId: 'ev-001', aasId: 'well-001', type: 'ARTIFACT_CREATED', timestamp: '2026-01-15T09:00:00Z', actor: 'Sarah Chen', actorRole: 'OperatorUser', description: 'W-1 permit application created', data: { artifactType: 'W-1' }, previousHash: '0000000000', hash: 'a1b2c3d4e5' },
    { eventId: 'ev-002', aasId: 'well-001', type: 'ARTIFACT_SUBMITTED', timestamp: '2026-01-15T09:30:00Z', actor: 'Sarah Chen', actorRole: 'OperatorUser', description: 'W-1 submitted for approval', data: { artifactId: 'art-001' }, previousHash: 'a1b2c3d4e5', hash: 'b2c3d4e5f6' },
    { eventId: 'ev-003', aasId: 'well-001', type: 'ARTIFACT_APPROVED', timestamp: '2026-01-16T14:00:00Z', actor: 'Diana Reeves', actorRole: 'Auditor', description: 'W-1 approved by auditor', data: { artifactId: 'art-001' }, previousHash: 'b2c3d4e5f6', hash: 'c3d4e5f6a7' },
    { eventId: 'ev-004', aasId: 'well-001', type: 'ARTIFACT_CREATED', timestamp: '2026-02-01T10:00:00Z', actor: 'Sarah Chen', actorRole: 'OperatorUser', description: 'W-2 potential test created', data: { artifactType: 'W-2' }, previousHash: 'c3d4e5f6a7', hash: 'd4e5f6a7b8' },
    { eventId: 'ev-005', aasId: 'well-002', type: 'ARTIFACT_REJECTED', timestamp: '2026-02-10T11:00:00Z', actor: 'Diana Reeves', actorRole: 'Auditor', description: 'W-1 rejected - missing formation data', data: { artifactId: 'art-004', reason: 'Missing formation interval' }, previousHash: 'd4e5f6a7b8', hash: 'e5f6a7b8c9' },
    { eventId: 'ev-006', aasId: 'well-001', type: 'SOD_VIOLATION_BLOCKED', timestamp: '2026-02-12T08:00:00Z', actor: 'Sarah Chen', actorRole: 'OperatorUser', description: 'SoD violation: submitter attempted self-approval', data: { artifactId: 'art-002', violation: 'sod-001', blocked: true }, previousHash: 'e5f6a7b8c9', hash: 'f6a7b8c9d0' },
    { eventId: 'ev-007', aasId: 'pad-001', type: 'INGESTION_COMPLETE', timestamp: '2026-02-22T06:00:00Z', actor: 'System', actorRole: 'System', description: 'SCADA data ingestion completed', data: { connector: 'SCADA', records: 1247 }, previousHash: 'f6a7b8c9d0', hash: 'a7b8c9d0e1' },
  ],
  connectors: [
    { connectorId: 'conn-001', name: 'Enverus DrillingInfo', type: 'API', status: 'ACTIVE', lastSync: '2026-02-22T04:00:00Z', recordCount: 45230, cadence: 'Daily 4AM CT', scope: 'Production, Permits, Completions' },
    { connectorId: 'conn-002', name: 'SCADA / Ignition', type: 'OPC-UA', status: 'ACTIVE', lastSync: '2026-02-22T07:55:00Z', recordCount: 1892340, cadence: 'Real-time (5 min)', scope: 'Pressures, Temps, Flow Rates' },
    { connectorId: 'conn-003', name: 'SAP ERP', type: 'RFC', status: 'ACTIVE', lastSync: '2026-02-21T23:00:00Z', recordCount: 12450, cadence: 'Nightly', scope: 'AFE, JIB, Revenue, Costs' },
    { connectorId: 'conn-004', name: 'Manual Upload Portal', type: 'File', status: 'ACTIVE', lastSync: '2026-02-20T15:30:00Z', recordCount: 89, cadence: 'On-demand', scope: 'RRC Filings, Reports, Certs' },
    { connectorId: 'conn-005', name: 'Texas RRC API', type: 'REST', status: 'ERROR', lastSync: '2026-02-19T04:00:00Z', recordCount: 3200, cadence: 'Weekly', scope: 'Permit Status, Violations, P-5' },
  ],
};
